### ISSUE TITLE
User and session management (CMS)

### ISSUE THREAD

**Issue by X-Ryl669** [kd2org/karadav#1]
I was wondering why a SQL database was required. I've found that you're using a DB mainly for storing the user's session and file's locks.

However, I've found this in the code:
https://github.com/kd2org/karadav/blob/381b498682214a07121dc6d81545020c35bd840a/lib/KaraDAV/Users.php#L251
Which, IMHO is wrong. Either you should store a file in a tmpfs (`/tmp`) and use its timestamp to know when last expiry happened and check it every call, but you can't rely on the server script being called at a specific time to trigger session deletions. You only have 1% chance (with the current code) that it'll happen so some session might linger for month or years depending on the server's usage.

I wonder if it's possible to:
1. Use an external script to validate users (like a CMS does in fact), so you don't care about session in your code. One can either use a default implementation of this script that'll fallback to LDAP or SQLite3's DB. Ideally, you should have a code that's creating the session object without triggering other thing elsewhere, so it can be called upon CMS' login. Once the user query the Webdav URL, it'll give a cookie that'll let you call `session_start()` on this with your object.
2. Use POSIX file locks instead of a SQL database ?
3. Allow to set the user's base path in the session (so that it's possible for a user to browse /home/joe). There are multiple security implication in doing this, since it means either letting `www-data user` access to the users' home directory (this is bad and dangerous in general) or using a proxy script to do that (like running a root's FTP server that's only listening on localhost and using [Flysystem](https://flysystem.thephpleague.com/docs/) to access user home with the identify of the user herself).

**Comment by bohwaz** [comment]
After thought about that config: this would require that your users have read/write access to the database file (not really a big issue) and read-only access to KaraDAV code.

To get back to the requirement for SQLite3:

* you could also just not implement file locks, like I do in Garradin, most webdav clients don't care if they locked a file and then it's not locked at next request, but then the litmus lock tests would all fail, and KaraDAV was developed to test litmus compliance
* you could also not store custom file properties as most webdav clients don't use them
* you could use something else for users sessions
* but you would still need to manage a list of app sessions, and SQLite3 is still better/faster at that than using a flat file

**Comment by X-Ryl669** [comment]
I don't think it's the right way to proceed. I think it's not good to have a `root` running webserver (like Apache) that can impersonate any user when requested `http://yourhost.com/files/1001/`. 

I'm using nginx because it drops its permission as soon as it's launched and can't reclaim them back.
There is no equivalent to mpm-itk in nginx (hopefully). We can start as many php-fpm spool as there are users (and run the spool as the user, each one having its own socket `/var/log/php-fpm/user1.sock`. 

But that means that the user now have complete control on the PHP server, so he can runs his own script if he wants and that's not very good, security wise. Typically, browsing to http://yourhost.com/files/bob/remoteShell.php will work and it's game over.

I'd a similar issue on my server and I've solved it by using FlySystem that's connecting to a inetd/vsftpd daemon only listening on localhost. This server drops its privileges as soon as it starts and setuid/gid to the asked user. Since it's a FTP server, it can only access files for reading, writing, listing directories. The risks are mitigated, but it's very slow, obviously. No X-SendFile in that case either.

I think a decent solution would be, instead, to use a program that's binding the user home folder as `www-data:www-data`. 
There is FUSE's bindfs doing so and it has decent performance. However, one does not want to have permanent bound mount on his system, so a small sudo-like program could be used to perfom this:

1. Upon session creation/login attempt:
1.1 Call the program with the provided user credentials (via `system()` or `popen`)
1.2 If the program validate the credentials, it forks and its child call [bindfs](https://bindfs.org/) with the right user mapping (user=>www-data) to a known temporary folder and write a time file token (like sudo is doing), then the parent returns success
1.3 Else, it fails and returns an error 
2. Upon session validation (or at regular interval), the program is called again with a `continue` parameter
2.1 If any time file token is found and the user name match, the file is touched to let the mount continue
2.2 Else if the time file token is too far in the past, the directory is unmounted (`fusermount -u`). We can even use the mount folder here, to avoid creating files.
3. In NGINX or Apache configuration, we can set alias folder to points to the mountpoints so X-SendFile is used
4. Upon session destruction, the program is called with a `umount` argument and it only `umount` the given's user mount.

This program should either be run as root or given setuid capability. Its attack surface should be very limited, since it's not doing anything on the files themselves. bindfs is very well tested and we can limit the attack surface by only binding with a restricted set of permissions (like `rD` or `rwD`) to prevent running any file on the mount bind. With the Alias directive, the files aren't visible to PHP-FPM as script either, they are only visible to the PHP's script (here: karadav) when using filesystem primitives. As long as the PHP code is doing what it claims, it should be safe.

**Comment by bohwaz** [comment]
You shouldn't let your web server config allow for CGI/script execution inside users directories obviously :)

So using one FPM pool per user and enabling script execution only on KaraDAV directory seems the most sensible way: easy enough to set up, and secure. But it won't scale very well with thousands of users.

But personally I've been using ITK for around 15 years, and some very large providers use it as well, and never had an issue, so I think it's a good solution, in fact it does the same as bindfs: it is dropping privileges as soon as possible.

**Comment by bohwaz** [comment]
I am closing this, as I have no intention of implementing that unless a PR is submitted. Thank your for your feedback.
