### ISSUE TITLE
Suggestion: release image to Docker Hub

### ISSUE THREAD

**Issue by sunjam** [kd2org/karadav#10]
Once you are ready you could make karadav available on https://hub.docker.com/

Great work on your project either way!

**Comment by bohwaz** [comment]
Thank you but  I can't, Docker is blocking me from creating an account, and there is no way to contact them.

Anyone is welcome to do that anyway.

**Comment by sunjam** [comment]
> Docker is blocking me from creating an account, and there is no way to contact them.

Blocking why?  Because of your IP location?

**Comment by bohwaz** [comment]
Yes my email address is blocked and my IP address is usually blocked by recaptcha, cloudflare and others as well. So I can't register, and I have no time to deal with that.
