### ISSUE TITLE
NextCloud Client: Internal Server Error

### ISSUE THREAD

**Issue by FlorianEndel** [kd2org/karadav#11]
I'm using KaraDAV 0.3.0 ([035793e](https://github.com/kd2org/karadav/commit/035793e7c4b2adca164a6bd9283442f0da0efd0d)) with docker on a Linux host. The container was built using the official dockerfile.

The service runs behind a reverse proxy (traefik) which handles TLS termination, routing, etc.
It is available on one of my domains (https://dav.domain.my).
Everything works fine:
- Webfrontend with different users & quotas
- Bookmark-Sync with floccus
- External Storage with NextCloud
- KDE Dolphin (with webdavs://dav.domain.my/files/user/ )

But syncing with NextCloud Desktop Client Version 3.6.1 (KDE) does not work. (Also tested with several older versions down to 2.6 with the exact same result.)

I was able to add a new account and login with the NextCloud client. It lists all available directories correctly. (The same NextCloud Desktop Client syncs flawlessly with my local NextCloud 25 instance behind the same Traefik reverse proxy and with a remote NextCloud 20 installation.)
The NextCloud Client identifies KaraDAV as NextCloud 24.0.4.1

The NextCloud Client displays the following error message:
  `Server replied with an error while reading directory "" : Error transferring https://dav.domain.my/remote.php/dav/files/user/ - server replied: Internal Server Error`

There is no error message in the container's log:

> [1] [Fri Nov  4 18:37:25 2022] 172.29.8.1:38482 Accepted
>   /remote.php/dav/files/florian/
>   [1] [Fri Nov  4 18:37:25 2022] 172.29.8.1:38482 Closing

On opening the URL `https://dav.domain.my/remote.php/dav/files/user/` in the browser, I have to provide my login credentials. After successful login the server responses with an `Error: 404 Not Found`

**Comment by bohwaz** [comment]
PHP errors are logged in the `error.log` file at the root of KaraDAV :)

Thank you for your report, I tried with NextCloud and fixed the issue, thank you. Please update to tag 0.3.1 and it should be fine :)
