### ISSUE TITLE
[bug] can't install - constant already defined 

### ISSUE THREAD

**Issue by t3dium** [kd2org/karadav#12]
![image](https://user-images.githubusercontent.com/83690012/200145904-ff1c02ff-161d-43a4-8a92-209b5af4a4fd.png)

also the same error when accessing from http://192.168.1.164:8080 

pic of the config.local.php

![image](https://user-images.githubusercontent.com/83690012/200145963-adc2b04f-2e66-4756-8e54-fc05711eca40.png)
is the only area i've changed, i also tried using the default config and ports, but same issue

(followed the docker install guide)

**Comment by bohwaz** [comment]
Just comment out the last line of your screenshot :)

**Comment by t3dium** [comment]
ah that worked, thank you
