### ISSUE TITLE
https not working - redirects to normal http ip when using reverse proxy

### ISSUE THREAD

**Issue by t3dium** [kd2org/karadav#13]
to use ssl with services i usually just make a rule in nginx proxy manager like this
![image](https://user-images.githubusercontent.com/83690012/200148048-f9d1ebde-8190-4edc-80fa-d886c479fb83.png)
![image](https://user-images.githubusercontent.com/83690012/200148060-9040bf22-8a3d-4ea1-a152-5ad8bc61159a.png)
![image](https://user-images.githubusercontent.com/83690012/200148070-a21b66d3-7e30-463b-a967-48070c5dde40.png)

however what's strange is that accessing karadav.box through that reverse proxy, just redirects me to the normal http ip? 
![image](https://user-images.githubusercontent.com/83690012/200148143-18dada7e-8b36-4eb7-a17a-6e7e98f0016f.png)
I also tried using port 445, (i changed 443 to 445 in the config), but it fails to access that entirely.

**Comment by bohwaz** [comment]
I don't know, I'm not using your setup, I'm using a apache proxy and it works well.

This is most likely a issue in your configuration. The only URL handled by KaraDAV is defined in WWW_URL, so once you're good on that, it should be OK.

I suggest you use your proxy debug logs and curl to see what's going on, but I cannot provide support on every specific tool you might use sorry.

**Comment by t3dium** [comment]
> This is most likely a issue in your configuration. The only URL handled by KaraDAV is defined in WWW_URL, so once you're good on that, it should be OK.

ah i found the issue now, https is working fine
