### ISSUE TITLE
[bug] webdav unuseable

### ISSUE THREAD

**Issue by t3dium** [kd2org/karadav#14]
mountain duck (based on cyberduck)
![image](https://user-images.githubusercontent.com/83690012/200149314-305ea5fb-1c36-4dbc-9d46-bc92c5273c45.png)

and using the nextcloud client (successfully opens browser and logs-in but can't sync files)
![image](https://user-images.githubusercontent.com/83690012/200149322-4064d722-5cb0-4ef2-adf6-c8790368cede.png)

also tried dolphin on another device and no luck

edit: owncloud clients also don't work

In case this was related to my reverse proxy, i also tried removing the reverse proxy entirely and connected over http with the ip, but still got the same errors

**installation method:** used docker guide

**Comment by bohwaz** [comment]
Please check the error.log file in karadav root directory to get the internal server error for the nextcloud client, after making sure you are using the latest release.

The HTTP 200 is an error coming from your proxy server I think, KaraDAV should reply either 500 (error) or 207, never 200.

**Comment by t3dium** [comment]
> The HTTP 200 is an error coming from your proxy server I think, KaraDAV should reply either 500 (error) or 207, never 200.

![image](https://user-images.githubusercontent.com/83690012/200150649-8e8c4b62-60b8-4bd4-b19e-0fc59281c1aa.png)

i removed the reverse proxy, by entering the direct ip in the config (as opposed to karadav.box, but i still get the same error

there's also no error.log file

**Comment by bohwaz** [comment]
Hum I looked again at the Cyberduck error and it seems it's a bug in their client as it seems to be doing a PROPFIND request on `/` which is not a webdav resource. The WebDAV URL is `/files/XXXX/`, it should not make a PROPFIND request on the root.

As for the nextcloud error, if there was an error in KaraDAV it would be in error.log at the root of Karadav, if not the 500 error is coming from somewhere else, like the HTTP proxy or the PHP HTTP server (look on the console for these).

**Comment by t3dium** [comment]
> As for the nextcloud error, if there was an error in KaraDAV it would be in error.log at the root of Karadav, if not the 500 error is coming from somewhere else, like the HTTP proxy or the PHP HTTP server (look on the console for these).

there's no error.log file, also karadav's currently running on a headless server so i can't view the server's screen, is there anything i can check over ssh?

**Comment by bohwaz** [comment]
The PHP HTTP server is logging to STDERR, so it depends on what you have configured.

You could just stop it and run "make server" as well, it will just launch a PHP HTTP server on port 8080, and you'll be able to see what's going on.

I'll try with Cyberduck if I can find a Windows PC at some point.

**Comment by bohwaz** [comment]
Thank you, I tested with Cyberduck and fixed the issue, everything should be fine with latest release :)
