### ISSUE TITLE
NextCloud/OwnCloud/Webclient: 500 Internal Server Error

### ISSUE THREAD

**Issue by trev0r-STA** [kd2org/karadav#19]
The error come:
1- when I want to create a new file
2- for existing file starting with a dot (hidden file in linux)

Debian 11, PHP 8.1, Nginx 1.18.0, NextCloud/OwnCloud latest version
data directory: permission's 770, owner/group www-data:www-data (db.sqlite owned by root)
Where could it come from ?

**Comment by bohwaz** [comment]
Please provide the error from `error.log`.

**Comment by trev0r-STA** [comment]
Which one ? The nginx server log or the karadav debug file ?

21 nov. 2022 22:39:18 BohwaZ ***@***.***>:

**Comment by bohwaz** [comment]
The error.log file inside KaraDAV root directory.

**Comment by trev0r-STA** [comment]
No error.log file in the karadav directory nor karadav/www... Should I activate something in the config.local.php ?

**Comment by bohwaz** [comment]
No there is nothing to activate by default.

If you don't have a error.log file this means the error is in the web server, not in KaraDAV, you should look at the error log of the file server.

**Comment by trev0r-STA** [comment]
Nothing in the error log file of the webserver :-(

**Comment by trev0r-STA** [comment]
> Maybe enable logs of your web server? I don't know your setup sorry.
Logs are enable, I've entry's# in karadav.access.log, but nothing in the karadav.error.log since the rotation of the logs the 22 novembre at 0:00

> If there's still nothing, does karadav has the right to write to its root directory?
/usr/local/share/karadav owner www-data:root and permissions set to 755

> You could try to update and configure the new option I added to choose where the error log should be saved? Maybe that will help?
> Or enable http debug log in KaraDAV to see what's going on, but it won't show the 500 error anyway.
With the new version and enabling the error.log, I discover my database was owned by root and not writable to www-data... I'm confused

**Comment by bohwaz** [comment]
No worries :)
