### ISSUE TITLE
Does not work with "Mountain Duck"

### ISSUE THREAD

**Issue by Kranf99** [kd2org/karadav#26]
everything is in the title

**Comment by bohwaz** [comment]
I don't have a Windows to try that, so what is the error? I tried with Cyber Duck and it worked a few months ago.

**Comment by Kranf99** [comment]
yes. Cyberduck works. ..But not Mountain Duck..

**Comment by bohwaz** [comment]
what is the error message? the log?

**Comment by bohwaz** [comment]
Closing as I don't have any info to work on.
