### ISSUE TITLE
Support for custom endpoint

### ISSUE THREAD

**Issue by MassiveBox** [kd2org/karadav#29]
Hello,  
I'm trying to install KaraDAV on my server.  

In my setup, I'm hosting a nice GUI for my files on `cloud.mysite.tld`, and I want to open a WebDAV endpoint on `cloud.mysite.tld/webdav`.
This is possible with other DAV servers like dave and docker-webdav.
I initially thought that it would be possible in KaraDAV as well, since there is an option to set up the base URL of the server (https://github.com/kd2org/karadav/blob/main/config.dist.php#L30), however I've set it to `https://cloud.mysite.tld/webdav` and it's ignored - if I open it on my browser I get a 404 error.  
I'm running the Docker container which I have just compiled.

I know that with KaraDAV it's slightly trickier than with other solutions because there is a whole web GUI, not just the WebDAV endpoint, but I believe it should be doable.
Feel free to ask if you need clarifications, and thanks for your work on KaraDAV!

**Comment by bohwaz** [comment]
You will need to use an apache `Alias` directive. See my last commit, I changed the code to allow this kind of setup. Tested and working :)

**Comment by MassiveBox** [comment]
While I assume this works great outside Docker, it seems to have the same problem with it. I still get the `Invalid URL` message and the `404` status code.

**Comment by bohwaz** [comment]
Invalid URL means that the URL is handled by KaraDAV but it is not recognized. Did you set the correct URL in config.local.php?

If yes, then I don't use docker sorry, you'll have to find a fix by yourself and post it here, I'll implement it if suitable :)
