### ISSUE TITLE
Support for auth scripts?

### ISSUE THREAD

**Issue by poVoq** [kd2org/karadav#33]
Would be nice if there was support for referencing small scripts to authenticate users against an API or an external database.

Specifically I would like to link this to my Fediverse instance similar to how it can be done with an XMPP server: https://docs.akkoma.dev/stable/configuration/integrations/howto_ejabberd/

(I am aware of the LDAP option, but it complicates user management too much otherwise).

Thanks!

**Comment by bohwaz** [comment]
Implemented, please test and report :)

**Comment by poVoq** [comment]
I am trying this now, but both my code and the function example returns an error like this:

```
TypeError
call_user_func(): Argument #1 ($callback) must be a valid callback, function "my_login" not found or invalid function name
```

**Comment by poVoq** [comment]
Ok I can get it somewhat to work with the class option when I add a `MyAuthClass.php` into the `/lib` folder with the following content:

```
<?php
class MyAuthClass {
        static function login(string $user, string $password) {
                return ($user == 'me' && $password == 'secret');
        }
}
```
However this only works with the correct `me` && `secret`. If you enter anything wrong the following error shows:
```
TypeError
KaraDAV\Users::login(): Return value must be of type ?stdClass, bool returned
```
which refers to the `return false;` in `/data/ssd/outmode/karadav/lib/KaraDAV/Users.php:170`

**Comment by poVoq** [comment]
Seems all working now :+1:  I shared my auth script for Akkoma here: 

https://meta.akkoma.dev/t/webdav-cloud-storage/466/2
