### ISSUE TITLE
CORS issues with reverse-proxy

### ISSUE THREAD

**Issue by poVoq** [kd2org/karadav#35]
I am not sure if this is actually an issue with Karadav or my nginx reverseproxy configuration.

However despite having set `const ACCESS_CONTROL_ALL = true;` I get a `CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 207` error in the browser when trying to access my otherwise working Karadav through the [Webdav-manager demo](https://kd2org.github.io/webdav-manager.js/demo.html).

I tried forcing the CORS header via my reverse-proxy (not an expert at all though) and then I get: 
`CORS header 'Access-Control-Allow-Origin' does not match '*, *'`

Maybe you got an idea what could be the ultimate source of this problem?

**Comment by bohwaz** [comment]
Not sure as cross-domain JS is always weird.

But WebDav Manager is already included in Karadav, you don't need to set it up separately.

**Comment by poVoq** [comment]
I only use it to test this as I might set up [Filestash](https://www.filestash.app/) later on if this works.

Anyway. Maybe I will find a solution tomorrow after researching a bit more. Thanks.
