### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by idunwannagotoschool** [kd2org/karadav#38]
Hello, I can’t get karadav installed properly.

I followed the instructions but it shows “Exception
Unable to open database: unable to open database file”.

![65A63A36-5952-4633-BB18-ADC0EAFF94D3](https://github.com/kd2org/karadav/assets/104383966/58fa93ba-d75a-4648-8998-d8637596ed2e)
![B4C1BE5D-437F-4AEC-9BF5-899C549CCB7D](https://github.com/kd2org/karadav/assets/104383966/5b5f10b6-d1d0-4c2f-9372-25be382ca7bf)

**Comment by bohwaz** [comment]
You probably just need to give write access to your web server on the "data" directory.
