### ISSUE TITLE
Configure per user quota and link to LDAP groups?

### ISSUE THREAD

**Issue by poVoq** [kd2org/karadav#4]
I can only see a way to configure the default storage quota, how can I configure that per user easily? Edit: ah I guess it's behind the "manage users" option on the web-interface?

Also a nice addition would be to link some different default quotas to LDAP groups.

Thanks!

**Comment by bohwaz** [comment]
> I can only see a way to configure the default storage quota, how can I configure that per user easily? Edit: ah I guess it's behind the "manage users" option on the web-interface?

Yes :) 

![image](https://user-images.githubusercontent.com/584819/198828868-c111a0a8-188f-44ee-a969-6179359d178d.png)

You also just change it in the database directly, using sqlite3 CLI:

`sqlite3 data/db.sqlite "UPDATE users SET quota = 300*1024*1024 WHERE login = 'demo';"`

(that's setting the quota to 300 MB for user demo).

> Also a nice addition would be to link some different default quotas to LDAP groups.

I'm not very familiar with LDAP so I don't know how to do that, but PRs are welcome.
