### ISSUE TITLE
Karadav: Option to use shared directories between users

### ISSUE THREAD

**Issue by ZsnZeeshan** [kd2org/karadav#40]
The idea is to use a symbolic link after creating a directory to share it between 2 or greater users. 
This will enable the users to share common directories of similar interests.

**Comment by bohwaz** [comment]
You can already do that manually, but there will be no UI in Karadav to do that sorry, as it implies having to manage rights: who has the right to create a symlink, and to whom, etc. And it's a quite some work to add this.
