### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by JarlMorgennebel** [kd2org/karadav#41]
Well...

it's a docker-compose.yml - technically. However, for people using docker and docker-compose you usually fire up the service with docker-compose up -d.

Which is not working here, you have to build it. And that requires the entire sources from GitHub. Not perfect...

Any chance to publish an working out of the box image on dockerhub which can be pulled and started in seconds?

Thanks.

**Comment by bohwaz** [comment]
The source is less than 300 KB, pulling from docker would probably be more than that ahah :)

I'm not using Docker myself, and don't have time to do more, feel free to do it :)

**Comment by JarlMorgennebel** [comment]
Understand and accept that.

However I do not want to have source and build tools on production servers. Production servers are stripped down, firewall protected bare metal users. Source files need to stay separate. So KaraDAV is not the right solution for me.

**Comment by bohwaz** [comment]
OK.
