### ISSUE TITLE
Ah right sorry, was probably the wrong link. But there is definitly something that prevents the Android app to recognize my Karadav server, while normal WebDAV used to work fine.

### ISSUE THREAD

**Issue by doesnmisclown** [kd2org/karadav#44]
Ah right sorry, was probably the wrong link. But there is definitly something that prevents the Android app to recognize my Karadav server, while normal WebDAV used to work fine.

But unrelated to this: Can you please re-open this issue? The web -based filemanager works fine after updating to 0.4.1, but the webdav access via (non-nextcloud) apps is still not working. It returns a 500 error.

Edit: hmmm, very odd. Oryzly does connect via webdav, but creates directories instead of the orgmode files, and then complaints that it can't sync because the file is a directory (409 error).

Edit: the same happens when I try to manually create text files via the web file manager. It gives an 500 error and when I refresh the page a directory has been created with the name of the text file that I tried to create.

_Originally posted by @poVoq in https://github.com/kd2org/karadav/issues/42#issuecomment-1763369632_
   
Reopened!

**Comment by bohwaz** [comment]
> Edit: hmmm, very odd. Oryzly does connect via webdav, but creates directories instead of the orgmode files, and then complaints that it can't sync because the file is a directory (409 error).

Fixed, try 0.4.2, thanks :)

**Comment by poVoq** [comment]
Confirmed, seems to be all working now (after manually deleting the directories that were created).

**Comment by bohwaz** [comment]
Even in Nextcloud app?

**Comment by poVoq** [comment]
No, that is an unrelated issue, likely related to my reverse-proxy setup.

**Comment by bohwaz** [comment]
OK, all good :) Let me know if you find another bug!

**Comment by doesnmisclown** [comment]
i don't understand: what should i do for connect to karadav with nextcloud app?
