### ISSUE TITLE
Empty "var" folder in each user directory

### ISSUE THREAD

**Issue by rdlmda** [kd2org/karadav#46]
I cloned the repo, built it on docker and ran it with

`docker run --rm -d -t --name karadav -p [port]:8080 -v $(pwd)/data:/var/karadav/data -v $(pwd)/config.local.php:/var/karadav/config.local.php karadav`

The only changes on my config.local.php are: 
```
const WWW_URL = 'https://[url:port]/';
const ERRORS_SHOW = false;
```

When I create a new user on the web interface, an empty `./data/[usernmame]` directory is created. But if I create or upload a new file either on the web interface or via a webdav client (I tested on Nemo v5.8.5), this `var` directory is created, in the sctructure, i.e. `data/bob/var/karadav/data/bob`.

Removing this empty folder has apparently no issues on file access, but uploading a new file or even overwriting an existing file (like editing it on notepad) recreates this empty folder.

**Comment by adamshand** [comment]
I just saw this in my installation as well and was trying to figure out what was going on.

**Comment by bohwaz** [comment]
It's probably a bug, I'll take a look, thanks :)
