### ISSUE TITLE
Nextcloud client not work

### ISSUE THREAD

**Issue by leonheart67** [kd2org/karadav#47]
Hello, i install karadav and it work with navigator or webdav acces, but not work properly with client nextcloud.
 Connection with client is ok, but cant see files/folder, and can't add files (touch "+" grey in nextcloud client, tested with different version of nextcloud client. 
I try with docker installation and with apache server directly. 
I don't have error in apache or karadav.

**Comment by bohwaz** [comment]
Release 0.4.3 should work again :)
