### ISSUE TITLE
e2ee support from Nextcloud app?

### ISSUE THREAD

**Issue by poVoq** [kd2org/karadav#5]
Has this been tested with the e2ee feature of the Nextcloud app?

https://nextcloud.com/de/endtoend/

I guess it might work, but maybe there could be official support for it like showing a locked icon or so in the webinterface for e2ee folders?

**Comment by bohwaz** [comment]
Not tested, and probably not supported. Not sure how this works, but is not something I'm interested in implementing personally.

The current implementation will always report that a file is unencrypted to the NC clients.

This seems to require the server to implement something: https://nextcloud.com/wp-content/webp-express/webp-images/uploads/2022/04/E2E-CreateAndSyncIdentity.png.webp

You are welcome to test and report if it works or not, but the goal of KaraDAV is not to replace NextCloud and all of its features, but to provide simple file sharing capability :)
