### ISSUE TITLE
Server replied "413 Request Entity Too Large" to PUT with Nextcloud apps on upload

### ISSUE THREAD

**Issue by poVoq** [kd2org/karadav#50]
With [this PR ](https://github.com/kd2org/karadav/pull/49) I got the Nextcloud apps to connect correctly to my KaraDAV behind Nginx, but somehow the apps fail to upload anything with a "413 Request Entity Too Large" error.

This might or might not be related to [this similar error](https://help.nextcloud.com/t/server-replied-413-request-entity-too-large-to-put/154278) with Nextcloud itself. But it happens on any file regardless of the size.

Uploading files with normal WebDAV apps or the built in web-client works.

Any idea what I could try to troubleshoot this? Thanks!

**Comment by bohwaz** [comment]
I'm quite certain this comes from your webserver (nginx), and not from KaraDAV, as there is nowhere in the code where 413 code is raised.

You can see here for some ideas on how to fix this: https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by poVoq** [comment]
Turns out it is an issue with the Nextcloud Android app and only over wifi. With mobile data it works and the desktop app is also working. Probably some odd setting or a bug.

Thanks anyways.

**Comment by bohwaz** [comment]
It might be trying to upload large files without using the "chunk" feature of the NextCloud API which splits large files in smaller chunks, leaving the server to reassemble the chunks.

This is definitely not an issue from KaraDAV though :) Good luck!
