### ISSUE TITLE
is it possible to add X-Accel-Redirect support

### ISSUE THREAD

**Issue by Infixz** [kd2org/karadav#51]
i searched X-Accel-Redirect in source code and found nothing only X-SENDFILE exist. i think nignx would not do anything to X-SENDFILE header. but nowadays, most ppl using nginx and depend on some plugin from nginx like ddns stuff. so is it possible to add x-accel header in this project?

**Comment by bohwaz** [comment]
I don't use nginx, as most people use Apache anyway, but feel free to propose a patch. But as far as I know X-Accel-Redirect doesn't allow to serve files outside of the document root, which will be an issue here.
