### ISSUE TITLE
401 Error | WebDAV 

### ISSUE THREAD

**Issue by einzelfabrik** [kd2org/karadav#54]
Hello, I am currently testing with Karadav, and find the speed and simplicity great. What I can't do is to upload data remotely with a webdav client. I have example.de/files/user as WEBDAV URL then I get login, but no matter how I log in I always get 401 - and can't authenticate myself. https://example.de/remote.php/webdav as well. Do you have any tips on how I can fix this, or what the cause is?

`{
    "installed": true,
    "maintenance": false,
    "needsDbUpgrade": false,
    "version": "99.0.0",
    "versionstring": "99.0.0",
    "edition": "",
    "productname": "NextCloud",
    "extendedSupport": false
}`

from error.log:
`ROUTER: => 401
Response headers:
  X-Powered-By: PHP/8.2.17
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
  Cache-Control: no-store, no-cache, must-revalidate
  Pragma: no-cache
  WWW-Authenticate: Basic realm="Please login"
`

**Comment by bohwaz** [comment]
This is probably a webserver misconfiguration issue where the HTTP 'Authorization' header is not transmitted by your webserver.

See https://stackoverflow.com/questions/51806446/serverhttp-authorization-is-missing

**Comment by einzelfabrik** [comment]
oh man, that was easy. here is my .htaccess with which it works right away!
`Options -Indexes -Multiviews
DirectoryIndex index.php

RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^.*$ /_router.php [L]
**SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1**
`

**Comment by einzelfabrik** [comment]
oh man, that was easy. here is my .htaccess with which it works right away!
```
Options -Indexes -Multiviews
DirectoryIndex index.php

RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^.*$ /_router.php [L]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

```
