### ISSUE TITLE
Missing SQLite3.php in lib folder

### ISSUE THREAD

**Issue by lhypds** [kd2org/karadav#55]
```
/!\ PHP error 
Warning: require_once(/var/www/webdav.xxxxxx.com/www/../lib/SQLite3.php): Failed to open stream: No such file or directory
#0 .../_inc.php(9)
#1 .../_inc.php(9)
#2 /var/www/webdav.gcc3.com/lib/KaraDAV/DB.php(5): KaraDAV\{closure}(string(7) "SQLite3")
#3 .../_inc.php(9): require_once(string(43) "/var/ww…)
#4 .../_inc.php(121): KaraDAV\{closure}(string(10) "KaraDAV…)
#5 .../_router.php(5): require_once(string(12) ".../_in…)
```

It seems in `lib` folder there is not a `SQLite3.php`

**Comment by bohwaz** [comment]
Do apt install php-sqlite3

**Comment by lhypds** [comment]
> Do apt install php-sqlite3

I've done `apt install php8.3-sqlite3` and `apt install php-sqlite3` both.
But still I got this error.

After installing the php-sqlite3, I cannot find (locate) the `SQLite3.php`.

**Comment by bohwaz** [comment]
There is no SQLite3.php in this project.

This error means that your sqlite3 PHP extension is not enabled. This has nothing to do with KaraDAV.

**Comment by lhypds** [comment]
Okay, so the problem is in `sqlite3 PHP extension`.
Got it, thank you.
