### ISSUE TITLE
Mirrored folder structure on SSD

### ISSUE THREAD

**Issue by Inkapa** [kd2org/karadav#56]
Hello, I love the project but I'm having a small issue that's confusing me.

I have karadav installed with Nginx on a raspberry pi 3 running DietPi (Debian 11), connected through USB is an SSD mounted to `/mnt/ssd`. For a given karadav `user`, the data folder at `/home/server/data/user/` is a symlink to `/mnt/ssd/user/`.

When `user` adds a new file, let's say `work/file.txt`, that is thus stored in `/mnt/ssd/user/work/file.txt`, a new **empty** folder structure appears in `/mnt/ssd/user/` that copies the home directory structure, like so: `/mnt/ssd/user/home/server/data/user/work/`.

Editing the `STORAGE_PATH` constant in `conf.dist.php` to `/mnt/ssd/` only changes the name of the mirrored folder once a new file is added (making it `/mnt/ssd/user/mnt/ssd/user/work/`)

And it only goes one way, as deleting the original `work/file.txt` does not delete the mirrored folder. I'm not sure if this is some kind of symlink trickery or messed up configuration, I'd just like to know how to stop it from doing that.

**Comment by bohwaz** [comment]
This bug was in a previous version, are you using the last version?

**Comment by Inkapa** [comment]
Ah indeed, it seems to be a duplicate of https://github.com/kd2org/karadav/issues/46

My bad, I didn't properly do my research, a simple `git pull` did the trick, thank you!
