### ISSUE TITLE
Problem with latest version and Docker: symlink to php binary missing

### ISSUE THREAD

**Issue by kalvn** [kd2org/karadav#58]
First of all, thanks a lot for this wonderful piece of software. It is very helpful!

I run my instance with Docker. I stick to your Dockerfile, just pushing my local config.

When trying to upgrade from 0.4.1 to 0.5.0 I faced this Docker error when starting my container:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "php": executable file not found in $PATH: unknown
```

After investigations, it appears the symlink from `/usr/bin/php82` to `/usr/bin/php` was missing.

So I modified my Dockerfile to add it after PHP installation:

```Dockerfile
...

# Add missing symlink
RUN ln -s /usr/bin/php82 /usr/bin/php

...
```

I'm not sure what's the root cause. I was maybe unlucky and ended-up downloading a bugged version of alpine:edge. I just wanted you to be aware of it. You might want to amend the Dockerfile, or just add a warning somewhere. Or simply ignore it. Up to you :)

**Comment by bohwaz** [comment]
This seems to be a docker issue, I'm not responsible for Docker bugs sorry :)

I'm considering removing docker files from this repo as it's creating a lot of issues, ideally someone should create a docker image, the software should not be responsible for handling this kind of distribution :(
