### ISSUE TITLE
Redirecting to 0.0.0.0:8080 when logout ore user change.

### ISSUE THREAD

**Issue by Archef2000** [kd2org/karadav#9]
When build using docker and port binding to example: `1234`  opening `10.10.15.52:1234` this loads the webdav server, but if you logout then you are redirected to `0.0.0.0:8080/login.php` and this persists until you manualy open `10.10.15.52:1234/login.php` 

second: 
On the main page under `WebDAV URL` is a link that always points to http://0.0.0.0:8080/files/<user\>/ 

third:
When in user managment and you change user name/pass and click `Save` you are redirected to `http://0.0.0.0:8080/users.php`

So my conclusion is that there are no dynamic links will try to make a PR.
PS: This persists with domains.

**Comment by bohwaz** [comment]
You have to manually configure the `WWW_URL` constant inside the `config.local.php`, as KaraDAV has no way of detecting the server address this way.

For example for testing I use:

```
const WWW_URL = 'http://192.168.43.171:8080/';
```

**Comment by Archef2000** [comment]
Yeah but would it not be better to have auto detection on the client side in case of a proxy or port mapping like docker.

**Comment by bohwaz** [comment]
There's auto-detection on the server side currently, the client cannot be trusted or it might open to flaws like open redirects.

I added instructions in INSTALL.md on how to configure WWW_URL accordingly.

If you have better detection code, then you're welcome for a PR, thank you :)

**Comment by Archef2000** [comment]
Because i dont see any client to server comunication for the path that is needed you cloud just use `window.location.origin` on the client which has no open redirect vuln

**Comment by bohwaz** [comment]
The redirect happens on the server side, so there is no safe way to get the URL from the client in a trusted way.

**Comment by Archef2000** [comment]
So why not just use a client side javascript and sanatize it befor display

**Comment by bohwaz** [comment]
There is no way to do that safely.
